CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS authors (
    id BIGSERIAL PRIMARY KEY,
    name CITEXT UNIQUE NOT NULL,
    bio VARCHAR(1024) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
